loom {
    runs {
        testmodClient {
            client()
            ideConfigGenerated project.rootProject == project
            name = "Testmod Client"
            source sourceSets.main
        }
        testmodServer {
            server()
            ideConfigGenerated project.rootProject == project
            name = "Testmod Server"
            source sourceSets.main
        }
    }

    fabricApi {
        configureDataGeneration {
            client = true
            modId = 'reservoir-testmod'
        }
    }
}

dependencies {
    api project(path: ':', configuration: 'namedElements')
    include project(':')
}